In [ ]:
import pandas as pd
dataset=pd.read_csv('DATMIN.csv')
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values
print(x)
print(y)

[['France' 33.0 7200.0]
 ['Spain' 44.0 5000.0]
 ['germany' 50.0 5500.0]
 ['Spain' 56.0 nan]
 ['germany' 30.0 6000.0]
 ['France' 40.0 6500.0]
 ['spain' nan 8000.0]
 ['france' 30.0 4000.0]
 ['germany' 33.0 3000.0]
 [nan 21.0 4000.0]]
['no' 'yes' 'no' 'yes' 'yes' 'yes' 'no' 'yes' 'no' 'yes']


In [ ]:
import numpy as np
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan,
						strategy ='mean')
data=[[ 33.0 ,7200.0],
 [44.0, 5000.0],
 [ 50.0 ,5500.0],
 [ 56.0, np.nan],
 [30.0 ,6000.0],
 [40.0, 6500.0],
 [np.nan,8000.0],
 [30.0 ,4000.0],
 [33.0 ,3000.0],
 [21.0, 4000.0]]

print (data)

imputer = imputer.fit(data)
data= imputer.transform(data)

print("Imputed Data: \n", data)

[[33.0, 7200.0], [44.0, 5000.0], [50.0, 5500.0], [56.0, nan], [30.0, 6000.0], [40.0, 6500.0], [nan, 8000.0], [30.0, 4000.0], [33.0, 3000.0], [21.0, 4000.0]]
Imputed Data: 
 [[  33.         7200.        ]
 [  44.         5000.        ]
 [  50.         5500.        ]
 [  56.         5466.66666667]
 [  30.         6000.        ]
 [  40.         6500.        ]
 [  37.44444444 8000.        ]
 [  30.         4000.        ]
 [  33.         3000.        ]
 [  21.         4000.        ]]


In [1]:
import pandas as pd
import numpy as np

dataset = pd.read_csv('DATMIN.csv');
print(dataset)
print(dataset.mean())
print(dataset.fillna(dataset.mean()))
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

   Country   Age  Salary Purchased
0   France  33.0  7200.0        no
1    Spain  44.0  5000.0       yes
2  germany  50.0  5500.0        no
3    Spain  56.0     NaN       yes
4  germany  30.0  6000.0       yes
5   France  40.0  6500.0       yes
6    spain   NaN  8000.0        no
7   france  30.0  4000.0       yes
8  germany  33.0  3000.0        no
9      NaN  21.0  4000.0       yes
Age         37.444444
Salary    5466.666667
dtype: float64
   Country        Age       Salary Purchased
0   France  33.000000  7200.000000        no
1    Spain  44.000000  5000.000000       yes
2  germany  50.000000  5500.000000        no
3    Spain  56.000000  5466.666667       yes
4  germany  30.000000  6000.000000       yes
5   France  40.000000  6500.000000       yes
6    spain  37.444444  8000.000000        no
7   france  30.000000  4000.000000       yes
8  germany  33.000000  3000.000000        no
9      NaN  21.000000  4000.000000       yes
[['France' 33.0 7200.0]
 ['Spain' 44.0 5000.0]
 ['germany' 50

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  import sys


In [2]:
import pandas as pd
import numpy as np
dataset = pd.read_csv('DATMIN.csv');
x = dataset.iloc[:, :-1].values

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])],remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 0.0 0.0 0.0 33.0 7200.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 44.0 5000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 50.0 5500.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 56.0 nan]
 [0.0 0.0 0.0 1.0 0.0 0.0 30.0 6000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 40.0 6500.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 nan 8000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 30.0 4000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 33.0 3000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 21.0 4000.0]]


In [3]:
import pandas as pd
import numpy as np

dataset = pd.read_csv('DATMIN.csv');

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
from sklearn.preprocessing import LabelEncoder
lbl = LabelEncoder()
y = lbl.fit_transform(y)
print(y)


[0 1 0 1 1 1 0 1 0 1]


In [6]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
dataset = pd.read_csv('DATMIN.csv');
bantu = dataset.fillna(dataset.mean())
array = bantu.values
X = array[:,1:3]
Y = array[:,0:3]

print(bantu) #untuk mengetahui bentuk tabel
print(X) #untuk mengetahui nilai array X
print(Y) #untuk mengetahui nilai array Y


dataset2=pd.DataFrame({'Country':array[:,0],'Age':array[:,1],'Salary':array[:,2],'Purchased':array[:,3]})
print("dataset sebelum dinormalisasi :")
print(dataset2.head(10))

min_max_scaler = preprocessing.MinMaxScaler(feature_range=(0,1)) #inisialisasi normalisasi MinMax
data = min_max_scaler.fit_transform(X) #transformasi MinMax untuk fitur
dataset2 = pd.DataFrame({'Age':data[:,0],'Salary':data[:,1],'Country':array[:,0],'Purchased':array[:,3]})

print("dataset setelah dinormalisasi :")
print(dataset2.head(10)) 


   Country        Age       Salary Purchased
0   France  33.000000  7200.000000        no
1    Spain  44.000000  5000.000000       yes
2  germany  50.000000  5500.000000        no
3    Spain  56.000000  5466.666667       yes
4  germany  30.000000  6000.000000       yes
5   France  40.000000  6500.000000       yes
6    spain  37.444444  8000.000000        no
7   france  30.000000  4000.000000       yes
8  germany  33.000000  3000.000000        no
9      NaN  21.000000  4000.000000       yes
[[33.0 7200.0]
 [44.0 5000.0]
 [50.0 5500.0]
 [56.0 5466.666666666667]
 [30.0 6000.0]
 [40.0 6500.0]
 [37.44444444444444 8000.0]
 [30.0 4000.0]
 [33.0 3000.0]
 [21.0 4000.0]]
[['France' 33.0 7200.0]
 ['Spain' 44.0 5000.0]
 ['germany' 50.0 5500.0]
 ['Spain' 56.0 5466.666666666667]
 ['germany' 30.0 6000.0]
 ['France' 40.0 6500.0]
 ['spain' 37.44444444444444 8000.0]
 ['france' 30.0 4000.0]
 ['germany' 33.0 3000.0]
 [nan 21.0 4000.0]]
dataset sebelum dinormalisasi :
   Country        Age       Salary Pur

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """
